### ISSUE TITLE
Resource fails with `open /root/.ssh/config: no such file or directory`

### ISSUE THREAD

**Issue by s2hc-johan** [concourse/hg-resource#17]
So I can't be 100% sure, but after a upgrade the other day, all our resources started failing with:

```
open /root/.ssh/config: no such file or directory
```
Looking at the change I would guess this change is the offender:

https://github.com/concourse/hg-resource/commit/75d02708b4bcbbccb88577efea1c81a59d1c32db#diff-539560c8bb7f0b5eb133bea29c18badb2943d366769fff45fb33a54120bde909R54

Looking at the previous `atomicSave` function it looks like it actually checks for the dir and creates it if it doesn't exists.

Are we doing anything wrong since we're using root, should we run as another user, should we have the go module create the dir if necessary or should we have the directory created in the docker file instead?

**Comment by vito** [comment]
Thanks for the report! Seems likely - I'll prioritize this. 👍

**Comment by s2hc-johan** [comment]
Could I help? Would you like the go application to create it if missing, or do you want the docker image to already have the directory?
