### ISSUE TITLE
Support username/password same way as git-resource

### ISSUE THREAD

**Issue by ergo** [concourse/hg-resource#2]
Hi,

I wanted to use hg-resource, using http username+tokens for authentication, but it seems that this is not really supported by this resource.

and when i tried to do:

```
uri: https://{{repo_hg_user}}:{{repo_hg_password}}@some-url
```

I actually ended up in something like:

```
https://"username":"password"@some-url
```

**Comment by epivenpro** [comment]
Hey there!
We'd love to have this feature as this is currently a blocker that prevents us from using concourse.

Is there an ETA by any chance?

**Comment by pegasd** [comment]
Hey there!
We'd love to have this feature as this is currently a blocker that prevents us from using concourse.

Is there an ETA by any chance?

**Comment by chendrix** [comment]
needs concourse/concourse#545

**Comment by jtarchie** [comment]
This can be accomplished with the new templating syntax using `(())`. 👍
