### ISSUE TITLE
Resource receiving revisions from a different branch

### ISSUE THREAD

**Issue by Fydon** [concourse/hg-resource#3]
I explicitly set the branch that the resource should be using, which in this case is default, but other branches which I'm creating from default are ending up on a pipeline, which then fails to use it with the following error:

```
abort: unknown revision 'x'!
Error checking out x: exit status 255`
```

I think this error is from [sourceRepo.GetCurrentCommitId](https://github.com/concourse/hg-resource/blob/master/hgresource/out.go#L47) in out.go, but I assume the problem is in check. Should the `hg log` calls in hg.go be using [`--branch`](https://www.selenic.com/mercurial/hg.1.html#log) to filter results to a certain branch, e.g [GetLatestCommitId](https://github.com/concourse/hg-resource/blob/master/hg/hg.go#L206) and [GetDescendantsOf](https://github.com/concourse/hg-resource/blob/master/hg/hg.go#L239)? How would I go about debugging this?

**Comment by jtarchie** [comment]
Looks like it was fixed in concourse/hg-resource#5
