### ISSUE TITLE
Cloning with subrepositories and other vcs

### ISSUE THREAD

**Issue by Krakonos** [concourse/hg-resource#8]
Hi!

I've been trying to set-up a concourse pipeline for a project of mine, and stumbled upon a problem: I can't clone a repository, that has git subrepositories. 

```
error: check failed with exit status '1':
abort: couldn't find git for subrepo 'XXX'
(check git is installed and in your PATH)
Error updating working directory to tip: exit status 255
```

I was digging around and it seems the docker image for this resource needs git, and perhaps other vcs tools.

Can this feature be added in some reasonable timeframe? I'm willing to install a custom version of hg-resource if you could provide a hint on how to do that.

**Comment by Krakonos** [comment]
Moreover, I could use the hggit plugin on other repository, as we use it in other project that will get included in the build system I'm currently setting up.

Thanks!

**Comment by jtarchie** [comment]
@Krakonos, please clarify why does `hg` need access to other VCSes. I am not aware of how it interacts with them.

**Comment by Krakonos** [comment]
Hi! Since Mercurial 1.5, mercurial repository can have git and svn (perhaps others, I'm not sure) subrepositories. See the Mercurial manual for more details: https://www.mercurial-scm.org/wiki/Subrepository

**Comment by jtarchie** [comment]
@Krakonos, we have to think about this because it adds a large binary dependency into the resource. For example, `git` requires Perl to use submodules.

Adding these dependencies can make the resource larger and therefore the distribution of concourse larger.

**Comment by jtarchie** [comment]
We have development instructions now on the `README.md`. You should be able to edit the `Dockerfile` and build your own image. It is all self contained. We are trying to make it easier for people to build most of our resources.

**Comment by jtarchie** [comment]
@Krakonos, we are not going to take on this work, sorry. After the discussion of the large binary dependencies, it would be too much to support. What if you need `git-lfs` with the git repo too? 😦 

We've provided instructions to build the image itself in the `README.md`. Please use that to build your own custom resource.

Cheers!
